default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV["DB_POOL"] || 5  %>
  database: <%= ENV['DB_NAME'] || 'gitlab-serverless-runner_development' %>
  username: <%= ENV['DB_USER'] || ENV['USER'] %>
  password: <%= ENV['DB_PASS'] %>
  host: <%= ENV["DB_HOST"] %>
  # url: <%= ENV['DATABASE_URL'] %> # takes higher precedence than other settings
  reconnect: true
  port: 5432

development:
  <<: *default
  database: <%= ENV['DB_NAME'] || 'gitlab-serverless-runner_development' %>

test:
  <<: *default
  database: gitlab-serverless-runner_test

production:
  <<: *default
  database: gitlab-serverless-runner_production
  url: <%= ENV['DATABASE_URL'] %>
